# Ansible Inventory - Auto-generated by Terraform
# Do not edit manually - this file is managed by Terraform

[webservers]
${public_ip}

[webservers:vars]
ansible_user=${ssh_user}
ansible_ssh_private_key_file=${private_key}
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

[all:vars]
# Global variables
env=dev
project=terraform-ansible-webapp
